/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StandbyRouteImport } from './routes/standby'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as ChangeTestCentreRouteImport } from './routes/change-test-centre'
import { Route as IndexRouteImport } from './routes/index'

const StandbyRoute = StandbyRouteImport.update({
  id: '/standby',
  path: '/standby',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeTestCentreRoute = ChangeTestCentreRouteImport.update({
  id: '/change-test-centre',
  path: '/change-test-centre',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-test-centre': typeof ChangeTestCentreRoute
  '/manage': typeof ManageRoute
  '/not-found': typeof NotFoundRoute
  '/standby': typeof StandbyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-test-centre': typeof ChangeTestCentreRoute
  '/manage': typeof ManageRoute
  '/not-found': typeof NotFoundRoute
  '/standby': typeof StandbyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-test-centre': typeof ChangeTestCentreRoute
  '/manage': typeof ManageRoute
  '/not-found': typeof NotFoundRoute
  '/standby': typeof StandbyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/change-test-centre' | '/manage' | '/not-found' | '/standby'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/change-test-centre' | '/manage' | '/not-found' | '/standby'
  id:
    | '__root__'
    | '/'
    | '/change-test-centre'
    | '/manage'
    | '/not-found'
    | '/standby'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangeTestCentreRoute: typeof ChangeTestCentreRoute
  ManageRoute: typeof ManageRoute
  NotFoundRoute: typeof NotFoundRoute
  StandbyRoute: typeof StandbyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/standby': {
      id: '/standby'
      path: '/standby'
      fullPath: '/standby'
      preLoaderRoute: typeof StandbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-test-centre': {
      id: '/change-test-centre'
      path: '/change-test-centre'
      fullPath: '/change-test-centre'
      preLoaderRoute: typeof ChangeTestCentreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangeTestCentreRoute: ChangeTestCentreRoute,
  ManageRoute: ManageRoute,
  NotFoundRoute: NotFoundRoute,
  StandbyRoute: StandbyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
